#!/usr/bin/env bash
# panel/render_markdown.sh — Render a stage JSON artifact as human-readable Markdown.
#
# Usage:
#   panel/render_markdown.sh <stage> <json_file>
#
# Writes to stdout. Caller redirects to <ARTIFACT>.md.
#
# Supported stages: attack-scenarios | requirements | risk-analysis | solutions | evaluator | cross-panel

set -euo pipefail

if [[ $# -lt 2 ]]; then
    echo "Usage: panel/render_markdown.sh <stage> <json_file>" >&2
    exit 1
fi

STAGE="$1"
JSON_FILE="$2"

if [[ ! -f "$JSON_FILE" ]]; then
    echo "ERROR: JSON file not found: ${JSON_FILE}" >&2
    exit 1
fi

if ! command -v jq >/dev/null 2>&1; then
    echo "ERROR: jq is required but not found in PATH" >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# Render helpers
# ---------------------------------------------------------------------------
render_attack_scenarios() {
    local json="$1"

    printf '# Attack Scenarios\n\n'
    printf '_Generated by ARES Stage 1 of the offensive panel pipeline._\n\n'

    # Summary block
    printf '## Summary\n\n'
    printf -- '- **Total scenarios**: %s\n' "$(printf '%s' "$json" | jq -r '.summary.count')"
    printf -- '- **Critical**: %s\n' "$(printf '%s' "$json" | jq -r '.summary.critical_count')"
    printf -- '- **Top chain**: %s\n' "$(printf '%s' "$json" | jq -r '.summary.top_chain_id')"
    printf -- '- **Attack classes covered**: %s\n\n' \
        "$(printf '%s' "$json" | jq -r '.summary.attack_classes_covered | join(", ")')"

    # Stage summary
    printf '## Stage Summary\n\n'
    printf '%s\n\n' "$(printf '%s' "$json" | jq -r '.stage_summary')"

    # Scenarios
    printf '## Scenarios\n\n'
    printf '%s' "$json" | jq -r '.scenarios[] |
        "## \(.id): \(.title)\n\n" +
        "- **Severity**: \(.severity)\n" +
        "- **Target rank**: \(.target_rank)/10\n" +
        "- **Novelty**: \(.novelty)/10\n" +
        (if .cve_refs and (.cve_refs | length) > 0 then "- **CVE refs**: \(.cve_refs | join(", "))\n" else "" end) +
        (if .prerequisites and (.prerequisites | length) > 0 then "- **Prerequisites**: \(.prerequisites | join("; "))\n" else "" end) +
        "\n**Objective**: \(.objective)\n\n" +
        "**Entry**: \(.entry)\n\n" +
        "**Primitives**:\n" +
        (.primitives | map("- \(.)") | join("\n")) + "\n\n" +
        "**Chain**: \(.chain)\n\n" +
        "**Defender visibility**: \(.defender_visibility)\n\n" +
        "**Evasion**: \(.evasion)\n\n" +
        "**Suggested test**: \(.suggested_test)\n\n" +
        "---\n"'
}

render_requirements() {
    local json="$1"

    printf '# Security Requirements\n\n'
    printf '_Generated by Stage 1 of the security panel pipeline._\n\n'

    # Summary block
    local count severity_dist high_lev
    count="$(printf '%s' "$json" | jq -r '.summary.count')"
    high_lev="$(printf '%s' "$json" | jq -r '.summary.highest_leverage_req_ids | join(", ")')"
    printf '## Summary\n\n'
    printf -- '- **Total requirements**: %s\n' "$count"
    printf -- '- **Critical**: %s | **High**: %s | **Medium**: %s | **Low**: %s\n' \
        "$(printf '%s' "$json" | jq -r '.summary.severity_distribution.critical')" \
        "$(printf '%s' "$json" | jq -r '.summary.severity_distribution.high')" \
        "$(printf '%s' "$json" | jq -r '.summary.severity_distribution.medium')" \
        "$(printf '%s' "$json" | jq -r '.summary.severity_distribution.low')"
    printf -- '- **Highest leverage**: %s\n\n' "$high_lev"

    # Stage summary
    printf '## Stage Summary\n\n'
    printf '%s\n\n' "$(printf '%s' "$json" | jq -r '.stage_summary')"

    # Requirements
    printf '## Requirements\n\n'
    printf '%s' "$json" | jq -r '.requirements[] |
        "### \(.id): \(.title)\n\n" +
        "- **Severity**: \(.severity)\n" +
        "- **Control area**: \(.control_area)\n" +
        "- **Verification**: \(.verification_method)\n" +
        "- **Target component**: \(.target_component)\n\n" +
        "**Description**: \(.description)\n\n" +
        "**Threat addressed**: \(.threat_addressed)\n" +
        (if .related_reqs then "**Related**: \(.related_reqs | join(", "))\n" else "" end) +
        (if .research_track_note then "**Research track**: \(.research_track_note)\n" else "" end) +
        "\n---\n"'
}

render_risk_analysis() {
    local json="$1"

    printf '# Risk Analysis\n\n'
    printf '_Generated by Stage 2 of the security panel pipeline._\n\n'

    # Summary
    printf '## Summary\n\n'
    printf -- '- **Critical**: %s | **High**: %s | **Medium**: %s | **Low**: %s\n' \
        "$(printf '%s' "$json" | jq -r '.summary.risk_count_by_rating.critical')" \
        "$(printf '%s' "$json" | jq -r '.summary.risk_count_by_rating.high')" \
        "$(printf '%s' "$json" | jq -r '.summary.risk_count_by_rating.medium')" \
        "$(printf '%s' "$json" | jq -r '.summary.risk_count_by_rating.low')"
    printf -- '- **Conditional count**: %s\n' \
        "$(printf '%s' "$json" | jq -r '.summary.conditional_count')"
    printf -- '- **Top high-leverage risks**: %s\n\n' \
        "$(printf '%s' "$json" | jq -r '.summary.top_high_leverage_ids | join(", ")')"

    # Stage summary
    printf '## Stage Summary\n\n'
    printf '%s\n\n' "$(printf '%s' "$json" | jq -r '.stage_summary')"

    # Risks
    printf '## Risks\n\n'
    printf '%s' "$json" | jq -r '.risks[] |
        "### \(.id): \(.title)\n\n" +
        "- **Verdict gate**: `\(.verdict_gate)`\n" +
        "- **Overall rating**: \(.overall_rating)\n" +
        "- **Exploitability**: \(.exploitability)/10 | **Impact**: \(.impact)/10 | **Detectability**: \(.detectability)/10 | **Novelty**: \(.novelty)/10\n" +
        "- **Maps to**: \(.maps_to_reqs | join(", "))\n" +
        "- **Linked test**: \(.linked_test_id)\n" +
        "- **High leverage**: \(.high_leverage)\n\n" +
        "**Attack vector**: \(.attack_vector)\n" +
        (if .condition then "**Condition**: \(.condition)\n" else "" end) +
        "\n---\n"'

    # Tests
    printf '\n## Red-Team Tests\n\n'
    printf '%s' "$json" | jq -r '.tests[] |
        "### \(.id): \(.title)\n\n" +
        "- **Type**: \(.test_type)\n" +
        "- **Tooling**: \(.tooling)\n" +
        "- **Validates**: \(.validates_risks | join(", "))\n\n" +
        "**Setup**: \(.setup)\n\n" +
        "**Procedure**: \(.procedure)\n\n" +
        "**Expected (vuln present)**: \(.expected_vuln_present)\n\n" +
        "**Expected (mitigated)**: \(.expected_mitigation_present)\n\n" +
        "**Pass criterion**: \(.pass_criterion)\n\n" +
        "---\n"'
}

render_solutions() {
    local json="$1"

    printf '# Solutions\n\n'
    printf '_Generated by Stage 3 of the security panel pipeline._\n\n'

    # Summary
    printf '## Summary\n\n'
    printf -- '- **P0**: %s | **P1**: %s | **P2**: %s\n' \
        "$(printf '%s' "$json" | jq -r '.summary.solution_count_by_priority.P0')" \
        "$(printf '%s' "$json" | jq -r '.summary.solution_count_by_priority.P1')" \
        "$(printf '%s' "$json" | jq -r '.summary.solution_count_by_priority.P2')"
    printf -- '- **Highest leverage solution**: %s\n' \
        "$(printf '%s' "$json" | jq -r '.summary.highest_leverage_sol')"
    printf -- '- **Total effort estimate**: %s hours\n\n' \
        "$(printf '%s' "$json" | jq -r '.summary.total_effort_hours')"

    # Stage summary
    printf '## Stage Summary\n\n'
    printf '%s\n\n' "$(printf '%s' "$json" | jq -r '.stage_summary')"

    # Roadmap
    printf '## Roadmap\n\n'
    printf '%s' "$json" | jq -r '.roadmap[] |
        "### Sprint \(.sprint) (~\(.total_hours_estimate)h)\n\n" +
        (.items | map("- \(.)") | join("\n")) + "\n\n"'

    # Solutions
    printf '## Solutions\n\n'
    printf '%s' "$json" | jq -r '.solutions[] |
        "### \(.id) [\(.priority)]: \(.title)\n\n" +
        "- **Priority**: \(.priority)\n" +
        "- **Effort**: \(.effort_hours)h\n" +
        "- **Targets risks**: \(.targets_risks | join(", "))\n" +
        "- **Targets reqs**: \(.targets_reqs | join(", "))\n" +
        "- **Validates test**: \(.validates_against_test)\n" +
        "- **Target file**: `\(.target_file)`\n\n" +
        "**Change**: \(.change_description)\n\n" +
        "**Does NOT defend against**: \(.does_not_defend_against)\n\n" +
        "---\n"'
}

render_evaluator() {
    local json="$1"

    printf '# Stage 4 — Evaluation\n\n'
    printf '_Generated by Stage 4 (evaluator) of the security panel pipeline._\n\n'

    # Verdict — prominently displayed
    local verdict
    verdict="$(printf '%s' "$json" | jq -r '.verdict')"
    if [[ "$verdict" == "PASS" ]]; then
        printf '**Verdict:** PASS\n\n'
    else
        printf '**Verdict:** NEEDS_WORK\n\n'
    fi

    # Coverage summary
    printf '## Coverage\n\n'
    printf 'Coverage: %s/%s reqs · %s/%s risks · %s P0 solutions\n\n' \
        "$(printf '%s' "$json" | jq -r '.coverage.reqs_covered')" \
        "$(printf '%s' "$json" | jq -r '.coverage.reqs_total')" \
        "$(printf '%s' "$json" | jq -r '.coverage.risks_addressed')" \
        "$(printf '%s' "$json" | jq -r '.coverage.risks_total')" \
        "$(printf '%s' "$json" | jq -r '.coverage.p0_sols_count')"

    # Findings count by severity
    printf '## Findings Summary\n\n'
    printf -- '- **Critical**: %s | **High**: %s | **Medium**: %s | **Low**: %s\n\n' \
        "$(printf '%s' "$json" | jq -r '.summary.findings_count_by_severity.critical')" \
        "$(printf '%s' "$json" | jq -r '.summary.findings_count_by_severity.high')" \
        "$(printf '%s' "$json" | jq -r '.summary.findings_count_by_severity.medium')" \
        "$(printf '%s' "$json" | jq -r '.summary.findings_count_by_severity.low')"

    # Decision rationale
    printf '**Decision rationale**: %s\n\n' \
        "$(printf '%s' "$json" | jq -r '.summary.decision_rationale')"

    # Stage summary
    printf '## Stage Summary\n\n'
    printf '%s\n\n' "$(printf '%s' "$json" | jq -r '.stage_summary')"

    # Findings — grouped by severity (critical first), rendered as table
    local finding_count
    finding_count="$(printf '%s' "$json" | jq '.findings | length')"
    if [[ "$finding_count" -gt 0 ]]; then
        printf '## Findings\n\n'
        for sev in critical high medium low; do
            local sev_count
            sev_count="$(printf '%s' "$json" | jq --arg s "$sev" '[.findings[] | select(.severity == $s)] | length')"
            if [[ "$sev_count" -gt 0 ]]; then
                printf '### %s\n\n' "$(printf '%s' "$sev" | tr '[:lower:]' '[:upper:]')"
                printf '%s' "$json" | jq -r --arg s "$sev" '.findings[] | select(.severity == $s) |
                    "#### \(.id): \(.category) — \(.referenced_artifact)/\(.referenced_id)\n\n" +
                    "- **Severity**: \(.severity)\n" +
                    "- **Category**: \(.category)\n" +
                    "- **References**: \(.referenced_artifact) \(.referenced_id)\n\n" +
                    "**Description**: \(.description)\n\n" +
                    "**Suggested remediation**: \(.suggested_remediation)\n\n" +
                    "---\n"'
            fi
        done
    else
        printf '## Findings\n\n_No findings — clean evaluation._\n\n'
    fi

    # Unevaluated (honesty field)
    printf '## Unevaluated\n\n'
    printf '%s\n\n' "$(printf '%s' "$json" | jq -r '.unevaluated')"
}

render_cross_panel() {
    local json="$1"

    printf '# Cross-Panel Reconciliation Report\n\n'
    printf '_Generated by the cross-panel reconciliation stage._\n\n'

    # Top-line summary table
    local both def_only off_only conflicts ratio ratio_pct
    both="$(printf '%s' "$json" | jq -r '.summary.both_count')"
    def_only="$(printf '%s' "$json" | jq -r '.summary.defensive_only_count')"
    off_only="$(printf '%s' "$json" | jq -r '.summary.offensive_only_count')"
    conflicts="$(printf '%s' "$json" | jq -r '.summary.conflict_count')"
    ratio="$(printf '%s' "$json" | jq -r '.summary.agreement_ratio')"
    ratio_pct="$(printf '%s' "$ratio" | awk '{printf "%.1f%%", $1 * 100}')"

    printf '## Summary\n\n'
    printf '| Metric | Value |\n'
    printf '|--------|-------|\n'
    printf '| Both panels | %s |\n' "$both"
    printf '| Defensive only | %s |\n' "$def_only"
    printf '| Offensive only | %s |\n' "$off_only"
    printf '| Conflicts | %s |\n' "$conflicts"
    printf '| Agreement ratio | %s |\n\n' "$ratio_pct"

    # Both panels section
    printf '## Both Panels\n\n'
    local both_count
    both_count="$(printf '%s' "$json" | jq '.both_panels | length')"
    if [[ "$both_count" -gt 0 ]]; then
        printf '%s' "$json" | jq -r '.both_panels[] |
            "- **\(.id)** [\(.consolidated_priority)]: \(.title)\n" +
            "  - Defensive: \(.defensive_sol_ids | join(", ")) · Offensive: \(.offensive_sol_ids | join(", "))\n" +
            "  - \(.description)\n"'
    else
        printf '_No defenses found in both panels._\n'
    fi
    printf '\n'

    # Defensive only section
    printf '## Defensive Only\n\n'
    local def_count
    def_count="$(printf '%s' "$json" | jq '.defensive_only | length')"
    if [[ "$def_count" -gt 0 ]]; then
        printf '%s' "$json" | jq -r '.defensive_only[] |
            "- **\(.id)**: \(.defensive_sol_ids | join(", "))\n" +
            "  - Rationale: \(.rationale)\n" +
            "  - Recommendation: \(.promote_recommendation)\n"'
    else
        printf '_No defenses found only in the defensive panel._\n'
    fi
    printf '\n'

    # Offensive only section
    printf '## Offensive Only\n\n'
    local off_count
    off_count="$(printf '%s' "$json" | jq '.offensive_only | length')"
    if [[ "$off_count" -gt 0 ]]; then
        printf '%s' "$json" | jq -r '.offensive_only[] |
            "- **\(.id)**: \(.offensive_sol_ids | join(", "))\n" +
            "  - Attacker leverage: \(.attacker_leverage_rationale)\n" +
            "  - Defensive gap: \(.defensive_gap_recommendation)\n"'
    else
        printf '_No defenses found only in the offensive panel._\n'
    fi
    printf '\n'

    # Conflicts section
    printf '## Conflicts\n\n'
    local conflict_count
    conflict_count="$(printf '%s' "$json" | jq '.conflicts | length')"
    if [[ "$conflict_count" -gt 0 ]]; then
        printf '%s' "$json" | jq -r '.conflicts[] |
            "- **\(.id)** [topic: \(.topic)]\n" +
            "  - Defensive position: \(.defensive_position)\n" +
            "  - Offensive position: \(.offensive_position)\n" +
            "  - Resolution: \(.recommended_resolution)\n"'
    else
        printf '_No conflicts — panels are aligned on priority and mechanism._\n'
    fi
    printf '\n'

    # Unevaluated (honesty field)
    printf '## Unevaluated\n\n'
    printf '%s\n\n' "$(printf '%s' "$json" | jq -r '.unevaluated')"

    # Stage summary
    printf '## Stage Summary\n\n'
    printf '%s\n\n' "$(printf '%s' "$json" | jq -r '.stage_summary')"
}

# ---------------------------------------------------------------------------
# Dispatch
# ---------------------------------------------------------------------------
JSON_CONTENT="$(cat "$JSON_FILE")"

case "$STAGE" in
    attack-scenarios)
        render_attack_scenarios "$JSON_CONTENT"
        ;;
    requirements)
        render_requirements "$JSON_CONTENT"
        ;;
    risk-analysis)
        render_risk_analysis "$JSON_CONTENT"
        ;;
    solutions)
        render_solutions "$JSON_CONTENT"
        ;;
    evaluator)
        render_evaluator "$JSON_CONTENT"
        ;;
    cross-panel)
        render_cross_panel "$JSON_CONTENT"
        ;;
    *)
        echo "ERROR: Unknown stage '${STAGE}'" >&2
        exit 1
        ;;
esac
