#!/usr/bin/env bash
# panel/render_markdown.sh — Render a stage JSON artifact as human-readable Markdown.
#
# Usage:
#   panel/render_markdown.sh <stage> <json_file>
#
# Writes to stdout. Caller redirects to <ARTIFACT>.md.
#
# Supported stages: attack-scenarios | requirements | risk-analysis | solutions

set -euo pipefail

if [[ $# -lt 2 ]]; then
    echo "Usage: panel/render_markdown.sh <stage> <json_file>" >&2
    exit 1
fi

STAGE="$1"
JSON_FILE="$2"

if [[ ! -f "$JSON_FILE" ]]; then
    echo "ERROR: JSON file not found: ${JSON_FILE}" >&2
    exit 1
fi

if ! command -v jq >/dev/null 2>&1; then
    echo "ERROR: jq is required but not found in PATH" >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# Render helpers
# ---------------------------------------------------------------------------
render_attack_scenarios() {
    local json="$1"

    printf '# Attack Scenarios\n\n'
    printf '_Generated by ARES Stage 1 of the offensive panel pipeline._\n\n'

    # Summary block
    printf '## Summary\n\n'
    printf -- '- **Total scenarios**: %s\n' "$(printf '%s' "$json" | jq -r '.summary.count')"
    printf -- '- **Critical**: %s\n' "$(printf '%s' "$json" | jq -r '.summary.critical_count')"
    printf -- '- **Top chain**: %s\n' "$(printf '%s' "$json" | jq -r '.summary.top_chain_id')"
    printf -- '- **Attack classes covered**: %s\n\n' \
        "$(printf '%s' "$json" | jq -r '.summary.attack_classes_covered | join(", ")')"

    # Stage summary
    printf '## Stage Summary\n\n'
    printf '%s\n\n' "$(printf '%s' "$json" | jq -r '.stage_summary')"

    # Scenarios
    printf '## Scenarios\n\n'
    printf '%s' "$json" | jq -r '.scenarios[] |
        "## \(.id): \(.title)\n\n" +
        "- **Severity**: \(.severity)\n" +
        "- **Target rank**: \(.target_rank)/10\n" +
        "- **Novelty**: \(.novelty)/10\n" +
        (if .cve_refs and (.cve_refs | length) > 0 then "- **CVE refs**: \(.cve_refs | join(", "))\n" else "" end) +
        (if .prerequisites and (.prerequisites | length) > 0 then "- **Prerequisites**: \(.prerequisites | join("; "))\n" else "" end) +
        "\n**Objective**: \(.objective)\n\n" +
        "**Entry**: \(.entry)\n\n" +
        "**Primitives**:\n" +
        (.primitives | map("- \(.)") | join("\n")) + "\n\n" +
        "**Chain**: \(.chain)\n\n" +
        "**Defender visibility**: \(.defender_visibility)\n\n" +
        "**Evasion**: \(.evasion)\n\n" +
        "**Suggested test**: \(.suggested_test)\n\n" +
        "---\n"'
}

render_requirements() {
    local json="$1"

    printf '# Security Requirements\n\n'
    printf '_Generated by Stage 1 of the security panel pipeline._\n\n'

    # Summary block
    local count severity_dist high_lev
    count="$(printf '%s' "$json" | jq -r '.summary.count')"
    high_lev="$(printf '%s' "$json" | jq -r '.summary.highest_leverage_req_ids | join(", ")')"
    printf '## Summary\n\n'
    printf -- '- **Total requirements**: %s\n' "$count"
    printf -- '- **Critical**: %s | **High**: %s | **Medium**: %s | **Low**: %s\n' \
        "$(printf '%s' "$json" | jq -r '.summary.severity_distribution.critical')" \
        "$(printf '%s' "$json" | jq -r '.summary.severity_distribution.high')" \
        "$(printf '%s' "$json" | jq -r '.summary.severity_distribution.medium')" \
        "$(printf '%s' "$json" | jq -r '.summary.severity_distribution.low')"
    printf -- '- **Highest leverage**: %s\n\n' "$high_lev"

    # Stage summary
    printf '## Stage Summary\n\n'
    printf '%s\n\n' "$(printf '%s' "$json" | jq -r '.stage_summary')"

    # Requirements
    printf '## Requirements\n\n'
    printf '%s' "$json" | jq -r '.requirements[] |
        "### \(.id): \(.title)\n\n" +
        "- **Severity**: \(.severity)\n" +
        "- **Control area**: \(.control_area)\n" +
        "- **Verification**: \(.verification_method)\n" +
        "- **Target component**: \(.target_component)\n\n" +
        "**Description**: \(.description)\n\n" +
        "**Threat addressed**: \(.threat_addressed)\n" +
        (if .related_reqs then "**Related**: \(.related_reqs | join(", "))\n" else "" end) +
        (if .research_track_note then "**Research track**: \(.research_track_note)\n" else "" end) +
        "\n---\n"'
}

render_risk_analysis() {
    local json="$1"

    printf '# Risk Analysis\n\n'
    printf '_Generated by Stage 2 of the security panel pipeline._\n\n'

    # Summary
    printf '## Summary\n\n'
    printf -- '- **Critical**: %s | **High**: %s | **Medium**: %s | **Low**: %s\n' \
        "$(printf '%s' "$json" | jq -r '.summary.risk_count_by_rating.critical')" \
        "$(printf '%s' "$json" | jq -r '.summary.risk_count_by_rating.high')" \
        "$(printf '%s' "$json" | jq -r '.summary.risk_count_by_rating.medium')" \
        "$(printf '%s' "$json" | jq -r '.summary.risk_count_by_rating.low')"
    printf -- '- **Conditional count**: %s\n' \
        "$(printf '%s' "$json" | jq -r '.summary.conditional_count')"
    printf -- '- **Top high-leverage risks**: %s\n\n' \
        "$(printf '%s' "$json" | jq -r '.summary.top_high_leverage_ids | join(", ")')"

    # Stage summary
    printf '## Stage Summary\n\n'
    printf '%s\n\n' "$(printf '%s' "$json" | jq -r '.stage_summary')"

    # Risks
    printf '## Risks\n\n'
    printf '%s' "$json" | jq -r '.risks[] |
        "### \(.id): \(.title)\n\n" +
        "- **Verdict gate**: `\(.verdict_gate)`\n" +
        "- **Overall rating**: \(.overall_rating)\n" +
        "- **Exploitability**: \(.exploitability)/10 | **Impact**: \(.impact)/10 | **Detectability**: \(.detectability)/10 | **Novelty**: \(.novelty)/10\n" +
        "- **Maps to**: \(.maps_to_reqs | join(", "))\n" +
        "- **Linked test**: \(.linked_test_id)\n" +
        "- **High leverage**: \(.high_leverage)\n\n" +
        "**Attack vector**: \(.attack_vector)\n" +
        (if .condition then "**Condition**: \(.condition)\n" else "" end) +
        "\n---\n"'

    # Tests
    printf '\n## Red-Team Tests\n\n'
    printf '%s' "$json" | jq -r '.tests[] |
        "### \(.id): \(.title)\n\n" +
        "- **Type**: \(.test_type)\n" +
        "- **Tooling**: \(.tooling)\n" +
        "- **Validates**: \(.validates_risks | join(", "))\n\n" +
        "**Setup**: \(.setup)\n\n" +
        "**Procedure**: \(.procedure)\n\n" +
        "**Expected (vuln present)**: \(.expected_vuln_present)\n\n" +
        "**Expected (mitigated)**: \(.expected_mitigation_present)\n\n" +
        "**Pass criterion**: \(.pass_criterion)\n\n" +
        "---\n"'
}

render_solutions() {
    local json="$1"

    printf '# Solutions\n\n'
    printf '_Generated by Stage 3 of the security panel pipeline._\n\n'

    # Summary
    printf '## Summary\n\n'
    printf -- '- **P0**: %s | **P1**: %s | **P2**: %s\n' \
        "$(printf '%s' "$json" | jq -r '.summary.solution_count_by_priority.P0')" \
        "$(printf '%s' "$json" | jq -r '.summary.solution_count_by_priority.P1')" \
        "$(printf '%s' "$json" | jq -r '.summary.solution_count_by_priority.P2')"
    printf -- '- **Highest leverage solution**: %s\n' \
        "$(printf '%s' "$json" | jq -r '.summary.highest_leverage_sol')"
    printf -- '- **Total effort estimate**: %s hours\n\n' \
        "$(printf '%s' "$json" | jq -r '.summary.total_effort_hours')"

    # Stage summary
    printf '## Stage Summary\n\n'
    printf '%s\n\n' "$(printf '%s' "$json" | jq -r '.stage_summary')"

    # Roadmap
    printf '## Roadmap\n\n'
    printf '%s' "$json" | jq -r '.roadmap[] |
        "### Sprint \(.sprint) (~\(.total_hours_estimate)h)\n\n" +
        (.items | map("- \(.)") | join("\n")) + "\n\n"'

    # Solutions
    printf '## Solutions\n\n'
    printf '%s' "$json" | jq -r '.solutions[] |
        "### \(.id) [\(.priority)]: \(.title)\n\n" +
        "- **Priority**: \(.priority)\n" +
        "- **Effort**: \(.effort_hours)h\n" +
        "- **Targets risks**: \(.targets_risks | join(", "))\n" +
        "- **Targets reqs**: \(.targets_reqs | join(", "))\n" +
        "- **Validates test**: \(.validates_against_test)\n" +
        "- **Target file**: `\(.target_file)`\n\n" +
        "**Change**: \(.change_description)\n\n" +
        "**Does NOT defend against**: \(.does_not_defend_against)\n\n" +
        "---\n"'
}

# ---------------------------------------------------------------------------
# Dispatch
# ---------------------------------------------------------------------------
JSON_CONTENT="$(cat "$JSON_FILE")"

case "$STAGE" in
    attack-scenarios)
        render_attack_scenarios "$JSON_CONTENT"
        ;;
    requirements)
        render_requirements "$JSON_CONTENT"
        ;;
    risk-analysis)
        render_risk_analysis "$JSON_CONTENT"
        ;;
    solutions)
        render_solutions "$JSON_CONTENT"
        ;;
    *)
        echo "ERROR: Unknown stage '${STAGE}'" >&2
        exit 1
        ;;
esac
